### ISSUE TITLE
These issues can be closed

### ISSUE THREAD

**Issue by wiibaa** [elasticsearch/logstash#2391]
* [x] #1482 as flushing was fix in #1545 and feature already described in #1231
* [x] #1629 as not supported in favor of using external tools
* [x] #1701 as moved to rake bootstrap
* [x] #1904 as fixed in logstash-plugins/logstash-input-elasticsearch/pull/6
* [x] #2185 fixed in 1.5 through #1545
* [x] #1765 fixed in 1.5 plugin architecture ?
* [x] #2123 fixed by almost merged logstash-plugins/logstash-filter-multiline/pull/4
* [x] #1413 wrongly created by user
* [ ] #2264 question answered
* [x] #2198 concerns logstash-forwarder
* [x] #1367 elasticsearch_http is deprecated + brand new improvment for bulk outputs/elasticsearch

**Comment by suyograo** [comment]
Thanks much @wiibaa .. cleaned up everything but #2264  -- will keep this open for longer
